// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// crecer_colonia_cpp
List crecer_colonia_cpp(LogicalMatrix estado, NumericMatrix g, NumericMatrix e, NumericMatrix N, NumericMatrix A, double theta0, double theta1, double omega2, double K_theta, double N_umbral, double p_max, double N_half, double mort_base, double mort_estres, double K_mort, double mutacion_sd, double sigma_e);
RcppExport SEXP _MPER_crecer_colonia_cpp(SEXP estadoSEXP, SEXP gSEXP, SEXP eSEXP, SEXP NSEXP, SEXP ASEXP, SEXP theta0SEXP, SEXP theta1SEXP, SEXP omega2SEXP, SEXP K_thetaSEXP, SEXP N_umbralSEXP, SEXP p_maxSEXP, SEXP N_halfSEXP, SEXP mort_baseSEXP, SEXP mort_estresSEXP, SEXP K_mortSEXP, SEXP mutacion_sdSEXP, SEXP sigma_eSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalMatrix >::type estado(estadoSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type g(gSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type e(eSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type N(NSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type theta0(theta0SEXP);
    Rcpp::traits::input_parameter< double >::type theta1(theta1SEXP);
    Rcpp::traits::input_parameter< double >::type omega2(omega2SEXP);
    Rcpp::traits::input_parameter< double >::type K_theta(K_thetaSEXP);
    Rcpp::traits::input_parameter< double >::type N_umbral(N_umbralSEXP);
    Rcpp::traits::input_parameter< double >::type p_max(p_maxSEXP);
    Rcpp::traits::input_parameter< double >::type N_half(N_halfSEXP);
    Rcpp::traits::input_parameter< double >::type mort_base(mort_baseSEXP);
    Rcpp::traits::input_parameter< double >::type mort_estres(mort_estresSEXP);
    Rcpp::traits::input_parameter< double >::type K_mort(K_mortSEXP);
    Rcpp::traits::input_parameter< double >::type mutacion_sd(mutacion_sdSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_e(sigma_eSEXP);
    rcpp_result_gen = Rcpp::wrap(crecer_colonia_cpp(estado, g, e, N, A, theta0, theta1, omega2, K_theta, N_umbral, p_max, N_half, mort_base, mort_estres, K_mort, mutacion_sd, sigma_e));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MPER_crecer_colonia_cpp", (DL_FUNC) &_MPER_crecer_colonia_cpp, 17},
    {NULL, NULL, 0}
};

RcppExport void R_init_MPER(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
