# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crecer_colonia_cpp <- function(estado, g, e, N, A, theta0 = 0.1, theta1 = 0.8, omega2 = 0.05, K_theta = 0.3, N_umbral = 0.15, p_max = 0.6, N_half = 0.3, mort_base = 0.01, mort_estres = 0.9, K_mort = 0.3, mutacion_sd = 0.02, sigma_e = 0.05) {
    .Call('_MPER_crecer_colonia_cpp', PACKAGE = 'MPER', estado, g, e, N, A, theta0, theta1, omega2, K_theta, N_umbral, p_max, N_half, mort_base, mort_estres, K_mort, mutacion_sd, sigma_e)
}

